name: dirajgoel
favicon: null
layout_spectrum: 0.39149
typography_spectrum: 0.17613
title: Drunk In The Enterprise
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#060606'
    - '#384449'
    - '#9e7e4c'
    - '#f5c271'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
