name: dirajgoel
favicon: null
layout_spectrum: 0.25793
typography_spectrum: 0.17613
title: Diraj Goel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfdfdf'
    - '#2f2f2f'
    - '#b5b5b5'
    - '#878787'
    - '#6b6b6b'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
